ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

RUN /usr/share/kibana/bin/kibana-plugin install /wazuh-app/wazuhapp/wazuh_kibana-4.4.4_7.17.9-1.zip
